const I={
egg:{name:'鸡蛋',emoji:'🥚',asset:null,wasteValue:1.2},tomato:{name:'番茄',emoji:'🍅',asset:null,wasteValue:2},rice:{name:'剩米饭',emoji:'🍚',asset:null,wasteValue:2.5},carrot:{name:'胡萝卜',emoji:'🥕',asset:null,wasteValue:1},milk:{name:'牛奶',emoji:'🥛',asset:null,wasteValue:4.8},onion:{name:'半颗洋葱',emoji:'🧅',asset:null,wasteValue:1.2},luncheon_meat:{name:'午餐肉',emoji:'🥓',asset:null,wasteValue:3},
corn:{name:'玉米',emoji:'🌽',wasteValue:null},cheese:{name:'芝士',emoji:'🧀',wasteValue:null},noodles:{name:'面条',emoji:'🍜',wasteValue:null},chicken_breast:{name:'鸡胸肉',emoji:'🍗',wasteValue:null},mushroom:{name:'蘑菇',emoji:'🍄',wasteValue:null},lettuce:{name:'生菜',emoji:'🥬',wasteValue:null},cucumber:{name:'黄瓜',emoji:'🥒',wasteValue:null},potato:{name:'土豆',emoji:'🥔',wasteValue:null},cabbage:{name:'白菜',emoji:'🥬',wasteValue:null},tofu:{name:'豆腐',emoji:'◻️',wasteValue:null},toast:{name:'吐司',emoji:'🍞',wasteValue:null},sausage:{name:'香肠',emoji:'🌭',wasteValue:null},banana:{name:'香蕉',emoji:'🍌',wasteValue:null},apple:{name:'苹果',emoji:'🍎',wasteValue:null},yogurt:{name:'酸奶',emoji:'🥣',wasteValue:null},broccoli:{name:'西兰花',emoji:'🥦',wasteValue:null},shrimp:{name:'虾仁',emoji:'🍤',wasteValue:null},spinach:{name:'菠菜',emoji:'🌿',wasteValue:null}
};
const DAY1_LAYOUT={milk:{left:6,top:7,width:21,height:18},egg:{left:7,top:29,width:24,height:19},luncheon_meat:{left:68,top:30,width:24,height:18},rice:{left:11,top:53,width:24,height:17},tomato:{left:7,top:72,width:24,height:20},carrot:{left:39,top:72,width:23,height:19},onion:{left:68,top:72,width:23,height:19}};
const R={te:['番茄炒蛋',{tomato:2,egg:1},2,8,80,280],fr:['蛋炒饭',{rice:1,egg:1,carrot:1},2,10,70,430],lcr:['午餐肉玉米炒饭',{rice:1,luncheon_meat:1,corn:1},2,9,60,470],me:['牛奶蒸蛋',{milk:1,egg:1},1,9,82,220],oe:['洋葱煎蛋',{onion:1,egg:1},1,7,72,180],ce:['芝士煎蛋',{cheese:1,egg:1},1,7,62,260],ten:['番茄鸡蛋面',{noodles:1,tomato:1,egg:1},2,8,76,470],cmo:['洋葱蘑菇鸡肉',{chicken_breast:1,mushroom:1,onion:1},2,12,88,390],ccs:['鸡肉玉米沙拉',{chicken_breast:1,lettuce:1,corn:1},2,6,94,320],pc:['土豆鸡肉煲',{potato:1,chicken_breast:1,carrot:1,onion:1},3,15,86,560],ct:['白菜豆腐汤',{cabbage:1,tofu:1,mushroom:1},2,10,90,240],tt:['番茄豆腐汤',{tomato:1,tofu:1},1,7,91,190],cut:['黄瓜拌豆腐',{cucumber:1,tofu:1},1,4,95,180],ecs:['鸡蛋黄瓜三明治',{toast:2,egg:1,cucumber:1},2,5,82,420],cst:['芝士香肠吐司',{toast:2,cheese:1,sausage:1},2,5,58,560],bm:['香蕉牛奶',{banana:1,milk:1},1,2,82,250],ay:['苹果酸奶杯',{apple:1,yogurt:1},1,2,90,190],bs:['西兰花炒虾仁',{broccoli:1,shrimp:1},2,8,96,260],cse:['玉米虾仁炒蛋',{corn:1,shrimp:1,egg:1},2,8,88,330],se:['菠菜鸡蛋汤',{spinach:1,egg:1},1,6,92,160]};
const L=[
[1,'先救番茄','万能食材也要省着用',{egg:3,tomato:2,rice:1,carrot:1,milk:1,onion:1,luncheon_meat:2},{tomato:2,rice:1,milk:1},['te','fr','me','oe'],{},s=>s.c>=.75,s=>s.c===1],
[2,'宿舍周末夜','不只有鸡蛋会被争抢',{toast:4,banana:1,milk:1,egg:1,cheese:2,sausage:1,cucumber:1,apple:1,yogurt:1},{toast:4,banana:1,milk:1},['me','ce','ecs','cst','bm','ay'],{},s=>s.u>=5,s=>s.c===1],
[3,'加班到家','今晚只想花 15 分钟',{noodles:1,tomato:1,spinach:1,egg:2,broccoli:1,shrimp:1,corn:1},{noodles:1,tomato:1,spinach:1},['ten','se','bs','cse'],{tm:15},s=>s.u>=2,s=>s.c===1&&s.t<=15],
[4,'两个人的晚餐','菜多不等于够吃',{chicken_breast:2,lettuce:1,mushroom:1,onion:1,potato:1,carrot:1,corn:1,tofu:1,tomato:1,cucumber:1},{chicken_breast:2,lettuce:1},['cmo','ccs','pc','tt','cut'],{sm:4},s=>s.s>=4,s=>s.s>=4&&s.c===1],
[5,'明早就出发','开第一锅前，先想最后一锅',{rice:1,tomato:3,tofu:1,banana:1,milk:1,luncheon_meat:1,corn:1,egg:1,onion:1},{rice:1,tomato:3,tofu:1,banana:1,milk:1},['te','lcr','me','oe','tt','bm'],{},s=>s.u>=5,s=>s.c===1],
[6,'减脂，但是不能浪费','同样清库存，做法也有代价',{chicken_breast:1,toast:2,apple:1,lettuce:1,corn:1,egg:1,cucumber:1,cheese:1,sausage:1,yogurt:1},{chicken_breast:1,toast:2,apple:1},['ccs','ecs','cst','ay','ce'],{cm:1000},s=>s.c===1,s=>s.c===1&&s.k<=1000],
[7,'朋友突然来了','真正关键的也许只是一个蘑菇',{chicken_breast:2,cabbage:1,tofu:1,potato:1,carrot:1,onion:1,mushroom:1,lettuce:1,corn:1,toast:2,egg:1,cucumber:1},{chicken_breast:2,cabbage:1,tofu:1},['cmo','ccs','pc','ct','cut','ecs','oe'],{sm:6},s=>s.s>=6,s=>s.s>=6&&s.c===1],
[8,'周日晚间备餐','毕业题：四类资源一起管',{tomato:3,milk:1,spinach:1,tofu:1,egg:4,rice:1,carrot:1,onion:1,shrimp:1,corn:1,toast:2,cucumber:1},{tomato:3,milk:1,spinach:1,tofu:1},['te','fr','me','oe','tt','cut','ecs','cse','se'],{tm:40,sm:7,cm:1250},s=>s.c===1,s=>s.c===1&&s.t<=40&&s.s>=7&&s.k<=1250]
];
let P=JSON.parse(localStorage.getItem('fridge_clear_v1')||'{"un":1,"best":{},"last":1}');
if(!P.tutorial||typeof P.tutorial!=='object')P.tutorial={basicDone:false};
let S=null,Q=null,timer=null,highlightTimer=null,dragState=null,suppressIngredientClickUntil=0;
const app=document.getElementById('app'),name=i=>I[i]?.name||i,emoji=i=>I[i]?.emoji||'🥣',ingredientVisual=i=>I[i]?.asset?`<img class="asset" src="${I[i].asset}" alt="">`:emoji(i),stars=n=>'★'.repeat(n)+'☆'.repeat(3-n),counts=a=>a.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{}),save=()=>localStorage.setItem('fridge_clear_v1',JSON.stringify(P)),el=id=>app.querySelector('#'+id);
function home(){S=Q=null;const l=L[Math.min(P.un,P.last||P.un)-1];app.innerHTML=`<section class="screen home"><div class="door"><div class="note"><h1>冰箱清空计划</h1><p>你的冰箱里没有剩菜，<br>只有还没被想出来的晚饭。</p></div><div class="current"><small>继续挑战 · DAY ${l[0]}</small><h2>${l[1]}</h2><div>${l[2]}</div></div><button class="primary" id="go">打开冰箱</button><div class="home-links"><button id="levels">关卡</button><button id="reset">重置进度</button></div></div></section>`;el('go').addEventListener('click',()=>start(l[0]));el('levels').addEventListener('click',levelPage);el('reset').addEventListener('click',()=>{if(window.confirm('重置全部关卡进度？')){localStorage.removeItem('fridge_clear_v1');location.reload()}})}
function page(title,sub,body){app.innerHTML=`<section class="screen page"><div class="page-head"><button class="back" aria-label="返回">‹</button><h1>${title}</h1></div><div class="sub">${sub}</div>${body}</section>`;app.querySelector('.back').addEventListener('click',home)}
function levelPage(){page('关卡','完成结算即可解锁下一关；三星不是门槛。',`<div class="levels">${L.map(l=>`<button class="level" data-day="${l[0]}" ${l[0]>P.un?'disabled':''}><span class="day-box">DAY<br>${l[0]}</span><span><h3>${l[1]}</h3><p>${l[2]}</p></span><span class="stars">${stars(P.best['d'+l[0]]||0)}</span></button>`).join('')}</div>`);app.querySelectorAll('[data-day]').forEach(x=>x.addEventListener('click',()=>start(+x.dataset.day)))}
function start(day){clearTimeout(highlightTimer);cleanupDrag();Q=L[day-1];S={inv:{...Q[3]},sel:[],done:[],m:{t:0,s:0,k:0},urgentTotal:Object.values(Q[4]).reduce((a,b)=>a+b,0),highlightIngredients:[],tutorial:day===1&&!P.tutorial?.basicDone?{phase:'select'}:null};P.last=day;save();renderGame()}
function renderGame(){app.innerHTML=`<section class="screen game"><header class="game-head"><div class="top"><span class="day">DAY ${Q[0]}</span><span class="game-title">${Q[1]}</span><button class="finish" id="finish">结束</button></div><div class="urgent"><b>今天必须处理</b><div id="urgentChips" class="urgent-chips"></div></div><div class="budgets" id="budgets"></div></header><section class="fridge" id="fridge"></section><section class="menu"><b>今晚菜单</b><span id="doneCount">0 道</span><div class="done" id="doneList"></div><button class="possible" id="possible">还能做</button></section><section class="cook" id="cookArea"><div class="hint" id="hint">点击食材放进料理区</div><div class="slots" id="slots"></div><div class="station"><div class="pot"></div><div class="actions"><button class="clear" id="clear">清空</button><button class="fire" id="fire">再想想</button></div></div></section><div class="toast" id="toast" role="status" aria-live="polite"></div><div class="tutorial-coach" id="tutorialCoach" role="status" aria-live="polite"></div><div class="shade" id="shade"></div><aside class="drawer" id="drawer"><div class="drawer-head"><b>今晚还能做</b><button class="close" id="closeDrawer">关闭</button></div><div id="recipeList"></div></aside><div class="modal-wrap" id="modalWrap"><div class="modal" id="modal"></div></div></section>`;el('finish').addEventListener('click',finishRequested);el('possible').addEventListener('click',()=>setDrawer(true));el('closeDrawer').addEventListener('click',()=>setDrawer(false));el('shade').addEventListener('click',()=>setDrawer(false));el('clear').addEventListener('click',()=>{S.sel=[];update()});el('fire').addEventListener('click',cook);update()}
function update(){renderUrgent();renderBudgets();renderIngredients();renderSlots();renderCookState();renderMenu();renderRecipes();renderTutorial();const finishBtn=el('finish'),done=remainingUrgent()===0;finishBtn.classList.toggle('ready',done);finishBtn.textContent=done?'完成今晚':'结束'}
function renderUrgent(){el('urgentChips').innerHTML=Object.entries(Q[4]).map(([i,n])=>{const q=Math.min(S.inv[i]||0,n);return q?`<span class="chip">${emoji(i)} ${name(i)}×${q}</span>`:''}).join('')||'<span class="chip">✓ 今天要救的东西都处理好了</span>'}
function renderBudgets(){const x=Q[6],a=[];if(x.tm)a.push(`<span class="${S.m.t>x.tm?'warn':''}">⏱ ${S.m.t}/${x.tm} 分钟</span>`);if(x.sm)a.push(`<span>👥 ${S.m.s}/${x.sm} 份</span>`);if(x.cm)a.push(`<span class="${S.m.k>x.cm?'warn':''}">🔥 ${S.m.k}/${x.cm} kcal</span>`);el('budgets').innerHTML=a.join('')}
function day1Position(i){const p=DAY1_LAYOUT[i];return p?`left:${p.left}%;top:${p.top}%;width:${p.width}%;height:${p.height}%;`:''}
function renderIngredients(){const fridge=el('fridge'),reserved=counts(S.sel),isDay1=Q[0]===1;fridge.innerHTML=Object.keys(Q[3]).map((i,j)=>{const q=S.inv[i]||0;if(!q)return'';const fixed=isDay1&&DAY1_LAYOUT[i],highlight=S.highlightIngredients?.includes(i);return`<button class="ingredient ${fixed?'day1-pos':'p'+(j%12)} ${(Q[4][i]||0)>0?'urgent-food':''} ${reserved[i]?'reserved':''} ${highlight?'recipe-highlight':''}" ${fixed?`style="${day1Position(i)}"`:''} data-ing="${i}" aria-label="${name(i)}，剩余 ${q}"><span class="icon">${ingredientVisual(i)}</span><span class="label">${name(i)}</span><span class="qty">×${q}</span></button>`}).join('');fridge.querySelectorAll('[data-ing]').forEach(bindIngredientInput)}
function bindIngredientInput(btn){const id=btn.dataset.ing;btn.addEventListener('click',e=>{if(Date.now()<suppressIngredientClickUntil){e.preventDefault();return}addIngredient(id)});btn.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;dragState={id,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,dragging:false,button:btn,ghost:null};btn.setPointerCapture?.(e.pointerId)});btn.addEventListener('pointermove',e=>{if(!dragState||dragState.pointerId!==e.pointerId||dragState.button!==btn)return;const dx=e.clientX-dragState.startX,dy=e.clientY-dragState.startY;if(!dragState.dragging&&Math.hypot(dx,dy)<8)return;if(!dragState.dragging){dragState.dragging=true;suppressIngredientClickUntil=Date.now()+450;btn.classList.add('dragging');const ghost=document.createElement('div');ghost.className='drag-ghost';ghost.innerHTML=`${ingredientVisual(id)}<small>${name(id)}</small>`;document.body.appendChild(ghost);dragState.ghost=ghost}e.preventDefault();moveDragGhost(e.clientX,e.clientY)});btn.addEventListener('pointerup',finishIngredientPointer);btn.addEventListener('pointercancel',finishIngredientPointer)}
function moveDragGhost(x,y){if(!dragState?.dragging)return;dragState.ghost.style.left=x+'px';dragState.ghost.style.top=y+'px';const r=el('slots').getBoundingClientRect(),inside=x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;el('cookArea').classList.toggle('drop-target',inside)}
function finishIngredientPointer(e){if(!dragState||dragState.pointerId!==e.pointerId)return;const state=dragState,r=el('slots').getBoundingClientRect(),inside=state.dragging&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;if(state.dragging){e.preventDefault();suppressIngredientClickUntil=Date.now()+450}cleanupDrag();if(inside)addIngredient(state.id)}
function cleanupDrag(){if(!dragState)return;dragState.button?.classList.remove('dragging');dragState.ghost?.remove();el('cookArea')?.classList.remove('drop-target');dragState=null}
function renderSlots(){const slots=el('slots');slots.innerHTML=Array.from({length:4},(_,j)=>S.sel[j]?`<div class="slot">${emoji(S.sel[j])}<button class="slot-x" aria-label="移除${name(S.sel[j])}" data-remove="${j}">×</button></div>`:'<div class="slot empty"></div>').join('');slots.querySelectorAll('[data-remove]').forEach(x=>x.addEventListener('click',()=>{S.sel.splice(+x.dataset.remove,1);update()}))}
function relation(r){const c=counts(S.sel);for(const[i,n]of Object.entries(c))if(n>(r[1][i]||0))return 0;const exact=Object.entries(r[1]).every(([i,n])=>(c[i]||0)===n)&&Object.keys(c).every(i=>r[1][i]!=null);return exact?2:1}
function matchedId(){return Q[5].find(id=>!S.done.includes(id)&&relation(R[id])===2)}
function canMake(r,inventory=S.inv){return Object.entries(r[1]).every(([i,n])=>(inventory[i]||0)>=n)}
function possibleIds(inventory=S.inv){return Q[5].filter(id=>!S.done.includes(id)&&canMake(R[id],inventory))}
function projection(r){const x=Q[6],nt=S.m.t+r[3],ns=S.m.s+r[2],nk=S.m.k+r[5],warn=!!((x.tm&&nt>x.tm)||(x.cm&&nk>x.cm)),bits=[];if(x.tm)bits.push(`+${r[3]}→${nt}/${x.tm}min${nt>x.tm?'⚠':''}`);if(x.sm)bits.push(`+${r[2]}份→${ns}/${x.sm}`);if(x.cm)bits.push(`+${r[5]}→${nk}/${x.cm}kcal${nk>x.cm?'⚠':''}`);return[warn,bits.length?' · '+bits.join(' · '):` · ${r[2]}份/${r[3]}分钟`]}
function renderCookState(){const fireBtn=el('fire'),hint=el('hint'),id=matchedId(),subset=Q[5].some(i=>relation(R[i])===1);fireBtn.classList.remove('ready');if(id){if(S.tutorial?.phase==='waitReady')S.tutorial.phase='fire';const r=R[id],p=projection(r);hint.innerHTML=r[0]+`<span style="font-size:8px;color:${p[0]?'#d34f37':'#68823f'}">${p[1]}</span>`;fireBtn.textContent='开火！';fireBtn.classList.add('ready')}else{hint.textContent=!S.sel.length?'放点什么进去试试。':subset?'好像能做点什么……':'这几样好像不太行。';fireBtn.textContent='再想想'}}
function renderMenu(){el('doneCount').textContent=S.done.length+' 道';el('doneList').innerHTML=S.done.map(i=>`<span>${R[i][0]}</span>`).join('');el('possible').textContent=`还能做 ${possibleIds().length} 道 ＞`}
function renderRecipes(){const recipeList=el('recipeList');recipeList.innerHTML=Q[5].map(id=>{const r=R[id],done=S.done.includes(id),ok=canMake(r)&&!done,p=projection(r),need=Object.entries(r[1]).map(([i,n])=>name(i)+'×'+n).join(' + ');return`<button type="button" class="recipe ${done||!ok?'off':p[0]?'warn':''}" ${done?'':`data-recipe-highlight="${id}"`}><span><span class="recipe-name">${r[0]}</span><span class="recipe-need">${need}</span><span class="recipe-meta">👥${r[2]} · ⏱${r[3]}${Q[6].cm?' · 🔥'+r[5]:''}</span></span><span class="recipe-state">${done?'已完成':ok?(p[0]?'会超目标':'可以做'):'做不了'}</span></button>`}).join('');recipeList.querySelectorAll('[data-recipe-highlight]').forEach(btn=>btn.addEventListener('click',()=>highlightRecipe(btn.dataset.recipeHighlight)))}
function highlightRecipe(id){clearTimeout(highlightTimer);S.highlightIngredients=Object.keys(R[id][1]).filter(i=>(S.inv[i]||0)>0);setDrawer(false);renderIngredients();renderTutorial();highlightTimer=setTimeout(()=>{if(!S)return;S.highlightIngredients=[];renderIngredients();renderTutorial()},800)}
function setDrawer(v){el('drawer').classList.toggle('show',v);el('shade').classList.toggle('show',v)}
function addIngredient(i){const c=counts(S.sel);if(S.sel.length>=4){showToast('锅里放不下更多了');return}if((S.inv[i]||0)<=(c[i]||0))return;S.sel.push(i);if(S.tutorial?.phase==='select')S.tutorial.phase='waitReady';update()}
function missingForRecipe(id,inventory=S.inv){return Object.entries(R[id][1]).filter(([i,n])=>(inventory[i]||0)<n).map(([i])=>i)}
function cook(){const id=matchedId();if(!id)return;const r=R[id];if(!canMake(r))return;const beforeInv={...S.inv},before=possibleIds(beforeInv),nextInv={...S.inv};for(const[i,n]of Object.entries(r[1])){if((nextInv[i]||0)<n)return;nextInv[i]-=n}S.inv=nextInv;S.done.push(id);S.sel=[];S.m.t+=r[3];S.m.s+=r[2];S.m.k+=r[5];const after=possibleIds(nextInv),closed=before.filter(x=>x!==id&&!after.includes(x)),depleted=Object.keys(r[1]).filter(i=>(beforeInv[i]||0)>0&&(nextInv[i]||0)===0),causalClosed=closed.filter(recipeId=>missingForRecipe(recipeId,nextInv).some(i=>depleted.includes(i))),causalDepleted=depleted.filter(i=>causalClosed.some(recipeId=>missingForRecipe(recipeId,nextInv).includes(i)));if(S.tutorial?.phase==='fire'){P.tutorial.basicDone=true;save();S.tutorial=null}update();if(causalClosed.length&&causalDepleted.length)showToast(`${causalDepleted.map(name).join('、')}用完了`,`${causalClosed.length} 道菜暂时做不了了`);else showToast(`${r[0]}完成`)}
function renderTutorial(){const coach=el('tutorialCoach');if(!coach)return;app.querySelectorAll('.tutorial-focus').forEach(x=>x.classList.remove('tutorial-focus'));coach.classList.remove('show');coach.textContent='';const phase=S.tutorial?.phase;if(!phase)return;if(phase==='select'){coach.textContent='点击或拖动食材，把它放进料理区。';coach.classList.add('show');el('fridge')?.classList.add('tutorial-focus');el('slots')?.classList.add('tutorial-focus')}else if(phase==='fire'){coach.textContent='配方凑齐了，开火试试。';coach.classList.add('show');el('fire')?.classList.add('tutorial-focus')}}
function remainingUrgent(){return Object.entries(Q[4]).reduce((s,[i,n])=>s+Math.min(S.inv[i]||0,n),0)}
function stats(){const remain=remainingUrgent(),used=S.urgentTotal-remain,clear=S.urgentTotal?used/S.urgentTotal:1,leftItems=[];Object.entries(Q[4]).forEach(([i,n])=>{const q=Math.min(S.inv[i]||0,n);if(q)leftItems.push({id:i,name:name(i),qty:q})});const avg=S.done.length?S.done.reduce((s,i)=>s+R[i][4],0)/S.done.length:0,grade=avg>=90?'S':avg>=75?'A':avg>=60?'B':'C',wasteKnown=leftItems.every(x=>Number.isFinite(I[x.id]?.wasteValue)),waste=wasteKnown?leftItems.reduce((sum,x)=>sum+I[x.id].wasteValue*x.qty,0):null,x={u:used,c:clear,t:S.m.t,s:S.m.s,k:S.m.k,leftItems,left:leftItems.map(x=>`${x.name}×${x.qty}`),waste,g:grade,d:S.done.length};x.star=1+(Q[7](x)?1:0)+(Q[8](x)?1:0);return x}
function finishRequested(){const s=stats();if(s.left.length){showModal(`<h2>今晚还有东西没处理</h2><p>${s.left.join('、')}</p><p>现在结束，它们会被算作浪费。</p><div class="modal-actions"><button class="secondary" id="cancelFinish">再看看</button><button class="primary" id="confirmFinish">就这样吧</button></div>`);el('cancelFinish').addEventListener('click',closeModal);el('confirmFinish').addEventListener('click',finishGame)}else finishGame()}
function finishGame(){const s=stats(),day1Perfect=Q[0]===1&&s.c===1,p=day1Perfect?['精算规划型','三个鸡蛋，一个都没白用。']:s.c===1?['极限清库存型','今天要救的食材，一个都没浪费。']:['明天再说型','差一点，冰箱里还有个小尾巴。'];P.best['d'+Q[0]]=Math.max(P.best['d'+Q[0]]||0,s.star);P.un=Math.max(P.un,Math.min(8,Q[0]+1));P.last=Q[0]<8?Q[0]+1:8;save();const wasteText=s.waste==null?'—':`¥${s.waste.toFixed(2)}`,leftover=s.left.length?`<div class="leftover">今晚留下：${s.left.join('、')}</div>`:'',mvp=day1Perfect?'今晚 MVP：鸡蛋':s.left.length?'今晚留下：'+s.left.join('、'):'今天要救的食材，一个都没浪费。',retryClass=s.c<1?'primary':'secondary',nextClass=s.c<1?'secondary':'primary';showModal(`<div>今晚的冰箱报告 · DAY ${Q[0]}</div><div class="score">${Math.round(s.c*100)}%</div><b>冰箱清空率</b><div class="stats"><div class="stat">浪费<b>${wasteText}</b></div><div class="stat">菜品<b>${s.d}道</b></div><div class="stat">营养<b>${s.g}</b></div><div class="stat">星级<b>${stars(s.star)}</b></div></div>${leftover}<div class="personality">${p[0]}</div><p>${p[1]}</p><div class="mvp">${mvp}</div><div class="modal-actions"><button class="${retryClass}" id="retryLevel">重新规划</button><button class="${nextClass}" id="nextLevel">${Q[0]<8?'下一关':'回到首页'}</button></div>`);el('retryLevel').addEventListener('click',()=>start(Q[0]));el('nextLevel').addEventListener('click',()=>Q[0]<8?start(Q[0]+1):home())}
function showModal(html){el('modal').innerHTML=html;el('modalWrap').classList.add('show')}
function closeModal(){el('modalWrap').classList.remove('show')}
function showToast(title,detail=''){const toast=el('toast');toast.innerHTML=`<div class="toast-title">${title}</div>${detail?`<div class="toast-detail">${detail}</div>`:''}`;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2400)}
home();
